[package]
name = "projet_step2"
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.3", features = ["atmega328p"] }

[profile.dev]
debug = true
panic = "abort"

[profile.release]
debug = true
panic = "abort"

# Section [bin] pour spécifier le fichier principal du programme
[[bin]]
name = "projet_step2"
path = "src/main_test.rs"

[unstable]
build-std = ["core"]


