[build]
target = "avr-unknown-gnu-atmega328"

[target.avr-unknown-gnu-atmega328]
linker = "avr-gcc"

rustflags = [
    "-C", "link-arg=-mmcu=atmega328",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-v"
]
